addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"                 % "1.4.2")
addSbtPlugin("com.geirsson"     % "sbt-ci-release"            % "1.5.3")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.4.0")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"                  % "2.2.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"       % "1.7.3")
