addSbtPlugin("com.dwijnand"              % "sbt-dynver"        % "3.3.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-release-early" % "2.1.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.1.6")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"      % "2.0.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"     % "1.5.1")
