addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"                 % "1.4.6")
addSbtPlugin("com.geirsson"     % "sbt-ci-release"            % "1.5.7")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"                  % "2.2.14")
